### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ShuxinLee** [wmn7/Universal_Light#7]
When installing aiolos, the corresponding version cannot be found. Is this library your team's self built library?

**Comment by wmn7** [comment]
Hello,

Thank you very much for your interest in our work. To answer your question, yes, **Aiolos is an internal library developed by SenseTime**. We do not plan to open-source it as it contains a significant amount of code related to our business operations.

However, we have open-sourced a repository with similar functionality, which you can find at https://github.com/Traffic-Alpha/TransSimHub. This repository has been stripped of business-specific code to make it more accessible.

**In addition, we're currently transitioning Universal_Light over to TransSimHub.** The foundational environment migration is complete, and we are poised to finish the migration of the training and testing components soon. To verify the environment and understand the agent design in our framework, you can execute the [check_tsc_env.py](https://github.com/wmn7/Universal_Light/blob/master/test/test_env/check_tsc_env.py) script. Please note that the current version includes some enhancements to the state representation which differ from the original paper. However, we've provided extensive comments to clarify these changes. Model weights and further code simplifications are on the horizon to improve clarity and ease of use.

Thank you once again for your interest in our work. Should you have any questions, please feel free to leave a message.

Best regards,

**Comment by wmn7** [comment]
Hello,

We're pleased to announce that the migration of the training and testing code has been completed. The README has been updated accordingly. We encourage you to utilize these resources. Currently, the repository provides the following:
- Code for model training: [train_UniTSA.py](https://github.com/wmn7/Universal_Light/blob/master/train_UniTSA.py)
- Code for model testing: [eval_model.py](https://github.com/wmn7/Universal_Light/blob/master/eval_model.py)

All road network data can be found in the [sumo_datasets](https://github.com/wmn7/Universal_Light/tree/master/sumo_datasets) directory, and model weights are stored in the [save_models](https://github.com/wmn7/Universal_Light/tree/master/save_models) directory. Please note that we have only uploaded a portion of the data for reference. For improved model performance, we recommend increasing the size of the training dataset, adjusting the training time, and further tuning the model parameters.

If you find our code useful, we kindly ask that you cite our paper in your work. Should you have any questions or encounter any issues, please do not hesitate to reach out to us.

Best Regards,
